package org.mifra.participants;

import org.mifra.core.api.models.domain.SagaStepHistory;
import org.mifra.core.api.models.domain.SagaStepMessage;
import org.mifra.core.api.models.domain.SagaStepOutcome;
import org.mifra.core.api.participant.Participant;
import org.mifra.messages.saga.AnalysisStepPayload;
import org.mifra.messages.saga.RequestPayload;

/**
 * This participant handles the analysis of the received external order request, currently with the sole function of
 * controlling if the order does not exceed the maximum allowed of 100 ordered units. This is the first participant to
 * be called in the demo saga.
 */
public class AnalysisParticipant implements Participant {

    /**
     * The method that handles a particular step can be named freely, but in order to be correctly registered as a
     * valid participant step, it must obey strict input and output rules.
     * @param history This is the complete history of all messages generated along the saga execution. At this point, it
     *                only contains one message, the initial message created by the orchestrator.
     * @return A saga step message that is appended to the saga step history. The class of its payload is also defined
     * here, which must implement SagaStepPayload. Also, this payload class must be unique to this participant step, it
     * cannot be reused by any other participant. This happens because the class name is how the framework associates
     * a saga step payload to a particular step. In this specific case, it means that while other participants can read
     * the AnalysisStepPayload object, only the analyse method of the AnalysisParticipant can generate it.
     */
    public SagaStepMessage<AnalysisStepPayload> analyse(SagaStepHistory history) {

        String resultState;

        /**
        This is the basic method of accessing the payload of past saga messages, by providing the class name of the
        required saga message. In this case, the RequestPayload generated by the orchestrator initially.
         */
        RequestPayload request = history.getStep(RequestPayload.class).getPayload();

        AnalysisStepPayload payload = new AnalysisStepPayload();

        if (request.getNoOfOrders() > 100) {
            resultState = "OverLimit";
        } else {
            resultState = "Valid";
        }

        SagaStepMessage<AnalysisStepPayload> message = new SagaStepMessage<>(payload);
        /**
        Here the step outcome is assigned, defined by the condition above. This instruction is essential for the
        framework to identify the next step to execute.
         */
        message.setResultState(SagaStepOutcome.of(resultState));

        return message;
    }
}
