package org.mifra.orchestrators;

import org.mifra.core.api.models.domain.SagaStepHistory;
import org.mifra.core.api.models.domain.SagaStepMessage;
import org.mifra.core.api.models.external.ExternalReply;
import org.mifra.core.api.models.external.ExternalRequest;
import org.mifra.core.api.orchestrator.Orchestrator;
import org.mifra.core.components.stepmaps.SagaStepMap;
import org.mifra.messages.external.ApprovalReplyBody;
import org.mifra.messages.external.ApprovalRequestBody;
import org.mifra.messages.saga.ApprovalStepPayload;
import org.mifra.messages.saga.RequestPayload;

/**
 * This class represents an implementation example of an orchestrator that receives a client request, directs it to the
 * appropriate saga, and prepares the reply to be returned to the client, via the three methods that are being
 * overridden below. It must implement the Orchestrator interface, and the classes that represent both the input and
 * output bodies of the external request and reply must be declared here as well, which must implement
 * ExternalRequestBody and ExternalReplyBody, respectively.
 * Here, the RequestApprovalOrchestrator takes an external request of which the body is deserialized into an
 * ApprovalRequestBody object, and the reply must be represented by an ApprovalReplyBody, which in turn, after the saga
 * processing is finished, is serialized by the framework and sent back to the client.
 */
public class RequestApprovalOrchestrator implements Orchestrator<ApprovalRequestBody, ApprovalReplyBody> {

    /**
     * The handleOncomingRequest method is a mandatory orchestrator method which processes the initial event of the
     * whole saga procedure, take the client request, prepare it into the standardized format for saga messages, and
     * return that message as the first resource to be used by it.
     * In this example, the orchestrator receives a request of which the body matches the deserialized format of
     * ApprovalRequestBody, and returns a SagaStepMessage object with a payload that must implement SagaStepPayload
     * (which in this case is RequestPayload). This message is the first message included in the SagaStepHistory object
     * that accompanies the saga's entire lifecycle, and it does not need to be a fixed class, the framework allows
     * different payload types encapsulated within a SagaStepMessage, as long as these implement the saga base payload
     * interface.
     * @param externalRequest The received external client request.
     * @return the first saga object to be handled by the business logic.
     */
    @Override
    public SagaStepMessage<?> handleOncomingRequest(ExternalRequest<ApprovalRequestBody> externalRequest) {

        RequestPayload payload = new RequestPayload(externalRequest.payload().getNoOfOrders());

        return new SagaStepMessage<>(payload);
    }

    /**
     * This mandatory method is triggered at the end of a saga, and is used to prepare the reply that is sent back to
     * the client. It receives the SagaStepHistory with all the messages generated by the various participants involved
     * in the saga, and returns the generated ExternalReply object, which includes the payload that will be returned to
     * the client, and must implement the ExternalReplyBody interface. In this particular example, ApprovalReplyBody
     * represents that payload. The ExternalReply object also contains a field dedicated to include custom http headers
     * to return, as well as the http status code.
     * @param sagaStepHistory The object that contains all the messages resulted from the saga.
     * @return the reply message that is returned to the client.
     */
    @Override
    public ExternalReply<ApprovalReplyBody> prepareExternalReply(SagaStepHistory sagaStepHistory) {

        ApprovalStepPayload lastStepPayload = sagaStepHistory.getStep(ApprovalStepPayload.class).getPayload();

        ApprovalReplyBody body = new ApprovalReplyBody();

        body.setDecision(lastStepPayload.getDecision());
        body.setDetails(lastStepPayload.getDetails());

        ExternalReply<ApprovalReplyBody> reply = new ExternalReply<>();
        reply.setPayload(body);
        reply.setStatus("200");

        return reply;

    }

    /**
     * This mandatory method is automatically called on bootstrap when registering an orchestrator. It defines the map
     * of saga steps in a graph format to a dedicated SagaStepMap object it receives. The saga step map is composed of
     * two main methods:
     * - setInitialStep, which defines the label for the first step of the saga, and does not require any additional
     * information.
     * - configureStep, applied to a given step label, and chained with one or multiple addStepResult methods, each of
     * them defining: the label of the step outcome for a given step, and the label for the next step to process.
     * @param sagaStepMap The map of saga steps to be defined on bootstrap.
     */
    @Override
    public void defineStepMap(SagaStepMap sagaStepMap) {

        /*
        This method call defines the first participant executed in the saga. This label matches the label of one of the
        participants that is registered during bootstrap.
        In the configuration phase of this demo application, the method analyse() of the participant
        "AnalysisParticipant" is registered with the label "OrderAnalysis". This label defined here creates the
        association between that registered participant and its location within the step map.
         */
        sagaStepMap.setInitialStep("OrderAnalysis");

        /*
        This method chain defines the behaviour of the step map after the OrderAnalysis step. First, configureStep
        defines which step is being set up, and both addStepResult methods define next possible steps depending on the
        step outcome received. The step outcome is defined by the participant and appended to the SagaStepMessage it
        produces, while the next step label matches the label for a registered participant. In common words, this chain
        reads as:
        - If the step OrderAnalysis produces the outcome "Valid", then the next step is OrderApproval.
        - If the step OrderAnalysis produces the outcome "OverLimit", then the next step is OrderTreatment.
         */
        sagaStepMap.configureStep("OrderAnalysis")
                .addStepResult("Valid","OrderApproval")
                .addStepResult("OverLimit","OrderTreatment");

        /*
        This method call to set up the OrderTreatment step is very similar to the one above, but in this case it only
        has one possible route to take: OrderTreatment produces the step Treated and the saga advances to OrderApproval.
         */
        sagaStepMap.configureStep("OrderTreatment")
                .addStepResult("Treated", "OrderApproval");

        /*
        When a given step in the step map does not have at least one configured next step, it's treated as a final
        step. After its execution is completed, the associated SagaStepHistory is handed back to the orchestrator to
        prepare the reply to send back to the client.
         */
    }
}
