package org.mifra.messages.saga;

import org.mifra.core.api.models.domain.payloads.SagaStepPayload;

/**
 * The AnalysisStepPayload that is generated by the analysis participant. Being a payload to include in a saga step
 * message, its only requirement is that it must implement SagaStepPayload.
 */
public class AnalysisStepPayload implements SagaStepPayload {

    private String handlingResult;

    public AnalysisStepPayload() {}

    public String getHandlingResult() {return handlingResult;}

    public void setHandlingResult(String handlingResult) {this.handlingResult = handlingResult;}

}
