package org.mifra.messages.saga;

import org.mifra.core.api.models.domain.payloads.SagaStepPayload;

/**
 * The ApprovalStepPayload that is generated by the approval participant. Being a payload to include in a saga step
 * message, its only requirement is that it must implement SagaStepPayload.
 */
public class ApprovalStepPayload implements SagaStepPayload {

    private String decision;
    private String details;

    public ApprovalStepPayload() {}

    public String getDecision() {return decision;}

    public void setDecision(String decision) {this.decision = decision;}

    public String getDetails() {return details;}

    public void setDetails(String details) {this.details = details;}
}
