package org.mifra.messages.saga;

import org.mifra.core.api.models.domain.payloads.SagaStepPayload;

/**
 * The RequestPayload that is generated by the orchestrator as the first message to include in the saga step history.
 * Being a payload to include in a saga step message, its only requirement is that it must implement SagaStepPayload.
 */
public class RequestPayload implements SagaStepPayload {

    private int receivedNoOfOrders;

    public RequestPayload() {}

    public RequestPayload(int receivedNoOfOrders) {this.receivedNoOfOrders = receivedNoOfOrders;}

    public int getNoOfOrders() {return receivedNoOfOrders;}

    public void setNoOfOrders(int receivedNoOfOrders) {this.receivedNoOfOrders = receivedNoOfOrders;}
}
