package org.mifra.messages.saga;

import org.mifra.core.api.models.domain.payloads.SagaStepPayload;

/**
 * The TreatmentStepPayload that is generated by the treatment participant. Being a payload to include in a saga step
 * message, its only requirement is that it must implement SagaStepPayload.
 */
public class TreatmentStepPayload implements SagaStepPayload {

    private int possibleOrder;

    public TreatmentStepPayload() {}

    public int getPossibleOrder() {return possibleOrder;}

    public void setPossibleOrder(int possibleOrder) {this.possibleOrder = possibleOrder;}
}
